### ISSUE TITLE
[Bug]: The latest version installed via pip is missing edk2basetools lib

### ISSUE THREAD

**Issue by Gaeric** [tianocore/edk2-basetools#124]
### Contact Details

1062217098@qq.com

### Describe the Bug

The latest version installed via pip (0.1.51) is missing edk2basetools and I cannot use this package to build edk2 via pip toolchain.
edk2 revision: 66c24219ade92b85b24f3ce29b988d187a9f6517

### Reproduction steps

1. pip install edk2-basetools
2. python -c "import edk2basetools"

3. For ref: pip install edk2-basetools==0.1.48; python -c "import edk2basetools"

### Expected behavior

python -c "import edk2basetools" is executed successfully and other tools run normally

### Execution Environment

python virtualenv: python 3.12

### Pip packages

edk2basetools==0.1.51

### Additional context

pip install edk2basetools==0.1.51
![image](https://github.com/tianocore/edk2-basetools/assets/15414688/1b812517-8bdb-40ab-aca9-69d61819eb2f)

pip install edk2basetools==0.1.48
![image](https://github.com/tianocore/edk2-basetools/assets/15414688/64f32f3b-a924-476c-98b7-b28274af5cd8)

**Comment by bcran** [comment]
It looks like this was broken in edk2-basetools version 0.1.50.

**Comment by bcran** [comment]
Sorry! I've fixed this in v0.1.52.
