### ISSUE TITLE
When install VS2019 if use VS2015 or VS2013 build will auto select VS2019

### ISSUE THREAD

**Issue by mini92** [tianocore/edk2-basetools#3]
When install VS2019 if use VS2015 or VS2013 build will auto select VS2019
![image](https://user-images.githubusercontent.com/13175278/104978686-66416a00-5a3d-11eb-8aa5-8fbe4f296bec.png)

**Comment by spbrogan** [comment]
sorry.  I need a lot more context.  What are you building.  How are you invoking it.  Can you provide full reproduction steps.

**Comment by mini92** [comment]
reproduction step:
Win10x64 
1.install Visual Studio 2013 use -t VS2013x86 build EdkII is ok
2.install Visual Studio 2015 use -t VS2013x86 or VS2015 build EDKII is ok
3.install Visual Studio 2019 use use -t VS2013 or VS2015 build EDK will auto slect VS2019 (as like image) and report err
4.if use VS2019 forcerebuild base tool ,use -t VS2019 build EDK is ok

**Comment by spbrogan** [comment]
I assume you are "building" the basetools C source files using https://github.com/tianocore/edk2/blob/master/BaseTools/toolsetup.bat?  If so this should be a bug/issue against that part of the project.  You can file it here.  https://bugzilla.tianocore.org/

**Comment by spbrogan** [comment]
I should also add here is a link that projects contribution process.  
https://github.com/tianocore/tianocore.github.io/wiki/How-To-Contribute
