### ISSUE TITLE
Running all unit tests causes the Split File tests to fail

### ISSUE THREAD

**Issue by corthon** [tianocore/edk2-basetools#6]
Current commit: b2bf904f4034259c9c40605de60e21c62f4601e1

If you run all of the pytest classes at once (via `pytest .`), the tests associated with the Split module will all fail. This failure seems to happen whether you run one test case or all test cases, but all tests succeed if run directly (with `pytest path_to_SplitTest.py`).

Seems to be an actual bug in Python when it comes to copying the filestat (inside `shutil.copy2`). Fails inside what I *think* is a curried function `_hookchmod`.

Happens on the very first iteration when copying the file.

Files exist and temp files exist, so failures in the tempfile module seem to be ruled out.

OS-independent, so it seems to be the same on Linux and Windows.

**Comment by BobCF** [comment]
This patch can resolve this problem.
https://github.com/tianocore/edk2-basetools/pull/7 

I'll send out a patch to edk2 community.
